//! Shape TypeScript language runtime extension.
//!
//! Provides a `shape.language_runtime` capability that embeds V8 via deno_core
//! for executing `foreign "typescript" { ... }` blocks in Shape programs.
//!
//! # ABI Exports
//!
//! All C ABI exports (`shape_plugin_info`, `shape_abi_version`,
//! `shape_capability_manifest`, `shape_capability_vtable`,
//! `shape_language_runtime_vtable`) are generated by the
//! [`shape_abi_v1::language_runtime_plugin!`] macro below.

pub mod error_mapping;
pub mod marshaling;
pub mod runtime;

shape_abi_v1::language_runtime_plugin! {
    name: c"typescript",
    version: c"0.1.0",
    description: c"TypeScript language runtime for foreign function blocks (V8 via deno_core)",
    vtable: {
        init: runtime::ts_init,
        register_types: runtime::ts_register_types,
        compile: runtime::ts_compile,
        invoke: runtime::ts_invoke,
        dispose_function: runtime::ts_dispose_function,
        language_id: runtime::ts_language_id,
        get_lsp_config: runtime::ts_get_lsp_config,
        free_buffer: runtime::ts_free_buffer,
        drop: runtime::ts_drop,
    }
}
