//! The lockfile-backed module loader (ADR-019 §4 / #198).
//!
//! Before this module a `fn typescript` body could not `import` anything at
//! all: the runtime installed no module loader, so V8 had nowhere to resolve a
//! specifier from. ADR-019 §4's requirement is not merely that imports work but
//! that they resolve from a LOCK — an import that reaches out to a registry at
//! run time is the TypeScript spelling of the virtualenv sniffing #198 deleted
//! on the Python side.
//!
//! So resolution here has exactly one source of truth: the `modules` table of
//! the declared lockfile, which maps the specifier a body writes to a vendored
//! file inside the declared environment root. A specifier that is not in the
//! table does not resolve — it is not searched for, and there is no filesystem
//! walk, no `node_modules`, and no network.
//!
//! # The boundary this slice draws
//!
//! What is here: specifier → vendored file, with `integrity` verified when the
//! lock declares it, and a structured refusal naming the lockfile otherwise.
//! Transitive imports work when the lock lists them too, because each nested
//! specifier goes back through the same table.
//!
//! What is NOT here, and why:
//!
//! - **No npm/registry resolution.** Producing a lockfile from a `package.json`
//!   is a resolver, which is a separate program; this is the half that makes a
//!   lockfile mean something at run time. Until a resolver exists, a lockfile is
//!   written or generated by other tooling.
//! - **No transpilation.** Vendored sources are loaded as JavaScript. The
//!   extension embeds V8, not the TypeScript compiler, and a loader that
//!   silently accepted `.ts` and shipped it to V8 would fail with a syntax error
//!   at a place that does not explain itself. A `.ts` path is refused at
//!   resolve time, naming pre-transpilation as the remedy.
//! - **No bare `import` statement in a fence.** A foreign body is compiled as a
//!   function body, not a module, so a top-level `import` is a syntax error
//!   before any of this is consulted. The spelling that reaches this loader is
//!   dynamic `await import("...")`.

use std::collections::BTreeMap;

/// One locked module: a specifier bound to a vendored file.
#[derive(Debug, Clone, PartialEq)]
pub struct LockedModule {
    /// Absolute path to the vendored source.
    pub path: String,
    /// `sha256-<hex>` over the file's bytes, verified at load when present.
    pub integrity: Option<String>,
}

/// The declared module map: everything a `fn typescript` body may import.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct LockedModules {
    modules: BTreeMap<String, LockedModule>,
}

impl LockedModules {
    pub fn new(modules: BTreeMap<String, LockedModule>) -> Self {
        Self { modules }
    }

    /// Read the module map out of the host's `init` config.
    ///
    /// Same envelope the Python side reads, under the `typescript` key: the
    /// host resolved the lockfile and verified the environment, and passes the
    /// resolved absolute paths.
    pub fn from_config(config_msgpack: &[u8]) -> Self {
        let Ok(config) = rmp_serde::from_slice::<serde_json::Value>(config_msgpack) else {
            return Self::default();
        };
        let Some(entries) = config
            .get(crate::modules::FOREIGN_ENVIRONMENTS_CONFIG_KEY)
            .and_then(|envs| envs.get("typescript"))
            .and_then(|env| env.get("modules"))
            .and_then(|m| m.as_object())
        else {
            return Self::default();
        };
        let mut modules = BTreeMap::new();
        for (specifier, value) in entries {
            let Some(path) = value.get("path").and_then(|p| p.as_str()) else {
                // A malformed entry is dropped rather than half-read: the
                // consequence is a refusal at the import, which says something
                // true, instead of a load from a path we guessed at.
                continue;
            };
            modules.insert(
                specifier.clone(),
                LockedModule {
                    path: path.to_string(),
                    integrity: value
                        .get("integrity")
                        .and_then(|i| i.as_str())
                        .map(str::to_string),
                },
            );
        }
        Self { modules }
    }

    pub fn is_empty(&self) -> bool {
        self.modules.is_empty()
    }

    pub fn get(&self, specifier: &str) -> Option<&LockedModule> {
        self.modules.get(specifier)
    }

    /// Every declared specifier, in canonical order — for diagnostics that can
    /// say what WAS available.
    pub fn specifiers(&self) -> Vec<&str> {
        self.modules.keys().map(|s| s.as_str()).collect()
    }

    /// Resolve a specifier to its vendored file, or say why not.
    ///
    /// Pure and V8-free, which is what lets the whole refusal set be tested
    /// without an isolate.
    pub fn resolve(&self, specifier: &str) -> Result<&LockedModule, ModuleRefusal> {
        let Some(locked) = self.modules.get(specifier) else {
            return Err(ModuleRefusal::NotLocked {
                specifier: specifier.to_string(),
                available: self.specifiers().iter().map(|s| s.to_string()).collect(),
            });
        };
        if locked.path.ends_with(".ts") || locked.path.ends_with(".tsx") {
            return Err(ModuleRefusal::NotTranspiled {
                specifier: specifier.to_string(),
                path: locked.path.clone(),
            });
        }
        Ok(locked)
    }

    /// Read a resolved module's source, verifying declared integrity.
    pub fn read(&self, locked: &LockedModule) -> Result<String, ModuleRefusal> {
        let bytes = std::fs::read(&locked.path).map_err(|e| ModuleRefusal::Unreadable {
            path: locked.path.clone(),
            detail: e.to_string(),
        })?;
        if let Some(declared) = &locked.integrity {
            let actual = sha256_integrity(&bytes);
            if &actual != declared {
                return Err(ModuleRefusal::IntegrityMismatch {
                    path: locked.path.clone(),
                    declared: declared.clone(),
                    actual,
                });
            }
        }
        String::from_utf8(bytes).map_err(|e| ModuleRefusal::Unreadable {
            path: locked.path.clone(),
            detail: e.to_string(),
        })
    }
}

/// `sha256-<lowercase hex>` over the given bytes.
fn sha256_integrity(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = String::with_capacity(7 + digest.len() * 2);
    out.push_str("sha256-");
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// The key the host hands environments under.
///
/// Mirrors `shape_runtime::project::FOREIGN_ENVIRONMENTS_CONFIG_KEY`; spelled
/// again because an extension links against `shape-abi-v1` only.
pub const FOREIGN_ENVIRONMENTS_CONFIG_KEY: &str = "shape_foreign_environments";

/// Why an import did not resolve.
#[derive(Debug, Clone, PartialEq)]
pub enum ModuleRefusal {
    /// The specifier is not in the lockfile's module table.
    NotLocked {
        specifier: String,
        available: Vec<String>,
    },
    /// The lock points at TypeScript source; this runtime embeds V8, not tsc.
    NotTranspiled { specifier: String, path: String },
    /// The vendored file could not be read.
    Unreadable { path: String, detail: String },
    /// The vendored file is not what the lock says it is.
    IntegrityMismatch {
        path: String,
        declared: String,
        actual: String,
    },
}

impl std::fmt::Display for ModuleRefusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotLocked {
                specifier,
                available,
            } => {
                write!(
                    f,
                    "import '{specifier}' is not in the declared typescript lockfile. A foreign \
                     body may only import what the lock resolves — nothing is searched for at \
                     run time."
                )?;
                if available.is_empty() {
                    write!(f, " The lock declares no modules.")
                } else {
                    write!(f, " Declared: {}.", available.join(", "))
                }
            }
            Self::NotTranspiled { specifier, path } => write!(
                f,
                "import '{specifier}' resolves to '{path}', which is TypeScript source. This \
                 runtime embeds V8, not the TypeScript compiler: vendor the transpiled \
                 JavaScript and lock that path instead."
            ),
            Self::Unreadable { path, detail } => {
                write!(f, "vendored module '{path}' could not be read: {detail}")
            }
            Self::IntegrityMismatch {
                path,
                declared,
                actual,
            } => write!(
                f,
                "vendored module '{path}' does not match the lock: declared {declared}, found \
                 {actual}."
            ),
        }
    }
}

impl std::error::Error for ModuleRefusal {}

#[cfg(test)]
mod tests {
    use super::*;

    fn locked(entries: &[(&str, &str, Option<&str>)]) -> LockedModules {
        LockedModules::new(
            entries
                .iter()
                .map(|(specifier, path, integrity)| {
                    (
                        specifier.to_string(),
                        LockedModule {
                            path: path.to_string(),
                            integrity: integrity.map(str::to_string),
                        },
                    )
                })
                .collect(),
        )
    }

    fn temp_file(contents: &str) -> std::path::PathBuf {
        let path = std::env::temp_dir().join(format!(
            "shape-198-mod-{}-{}.js",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::write(&path, contents).expect("write");
        path
    }

    #[test]
    fn a_locked_specifier_resolves_to_its_vendored_file() {
        let modules = locked(&[("./util", "/vendor/util.js", None)]);
        let resolved = modules.resolve("./util").expect("locked");
        assert_eq!(resolved.path, "/vendor/util.js");
    }

    #[test]
    fn an_unlocked_specifier_is_refused_and_says_what_was_declared() {
        let modules = locked(&[("./util", "/vendor/util.js", None)]);
        let err = modules.resolve("lodash").expect_err("not locked");
        assert!(matches!(err, ModuleRefusal::NotLocked { .. }));
        let message = err.to_string();
        assert!(message.contains("lodash"), "got: {message}");
        assert!(
            message.contains("nothing is searched for at run time"),
            "the refusal must state the rule, got: {message}"
        );
        assert!(
            message.contains("./util"),
            "a refusal that lists what WAS available is the one a user can act on: {message}"
        );
    }

    #[test]
    fn an_empty_lock_refuses_every_import() {
        let modules = LockedModules::default();
        assert!(modules.is_empty());
        let message = modules
            .resolve("./anything")
            .expect_err("empty")
            .to_string();
        assert!(message.contains("declares no modules"), "got: {message}");
    }

    #[test]
    fn typescript_source_is_refused_with_the_remedy() {
        let modules = locked(&[("./util", "/vendor/util.ts", None)]);
        let err = modules.resolve("./util").expect_err("not transpiled");
        assert!(matches!(err, ModuleRefusal::NotTranspiled { .. }));
        assert!(
            err.to_string().contains("vendor the transpiled JavaScript"),
            "got: {err}"
        );
    }

    #[test]
    fn a_vendored_module_reads_when_integrity_matches() {
        let path = temp_file("export const answer = 42;\n");
        let integrity = sha256_integrity(b"export const answer = 42;\n");
        let modules = locked(&[("./answer", path.to_str().unwrap(), Some(integrity.as_str()))]);
        let resolved = modules.resolve("./answer").expect("locked");
        let source = modules.read(resolved).expect("integrity holds");
        let _ = std::fs::remove_file(&path);
        assert!(source.contains("answer = 42"));
    }

    #[test]
    fn a_tampered_vendored_module_is_refused() {
        let path = temp_file("export const answer = 43;\n");
        // Integrity of the file we MEANT to vendor.
        let integrity = sha256_integrity(b"export const answer = 42;\n");
        let modules = locked(&[("./answer", path.to_str().unwrap(), Some(integrity.as_str()))]);
        let resolved = modules.resolve("./answer").expect("locked");
        let err = modules.read(resolved).expect_err("integrity fails");
        let _ = std::fs::remove_file(&path);
        assert!(matches!(err, ModuleRefusal::IntegrityMismatch { .. }));
        assert!(err.to_string().contains("does not match the lock"), "{err}");
    }

    #[test]
    fn a_module_without_declared_integrity_still_reads() {
        // Integrity is optional in the lock; its absence must not become a
        // refusal, or a lock written by hand is unusable.
        let path = temp_file("export const answer = 42;\n");
        let modules = locked(&[("./answer", path.to_str().unwrap(), None)]);
        let resolved = modules.resolve("./answer").expect("locked");
        let source = modules.read(resolved).expect("reads");
        let _ = std::fs::remove_file(&path);
        assert!(source.contains("42"));
    }

    #[test]
    fn the_module_map_is_read_from_the_hosts_config() {
        let config = rmp_serde::to_vec(&serde_json::json!({
            FOREIGN_ENVIRONMENTS_CONFIG_KEY: {
                "typescript": {
                    "runtime": "deno",
                    "modules": {
                        "./util": { "path": "/vendor/util.js", "integrity": "sha256-aa" }
                    }
                }
            }
        }))
        .expect("encodes");
        let modules = LockedModules::from_config(&config);
        let resolved = modules.resolve("./util").expect("locked");
        assert_eq!(resolved.path, "/vendor/util.js");
        assert_eq!(resolved.integrity.as_deref(), Some("sha256-aa"));
    }

    #[test]
    fn another_languages_environment_declares_no_typescript_modules() {
        let config = rmp_serde::to_vec(&serde_json::json!({
            FOREIGN_ENVIRONMENTS_CONFIG_KEY: {
                "python": { "search_paths": ["/proj/.venv/lib/python3.11/site-packages"] }
            }
        }))
        .expect("encodes");
        assert!(LockedModules::from_config(&config).is_empty());
    }

    #[test]
    fn an_absent_or_garbled_config_declares_nothing() {
        assert!(LockedModules::from_config(&[]).is_empty());
        assert!(LockedModules::from_config(b"not msgpack").is_empty());
        assert!(
            LockedModules::from_config(&rmp_serde::to_vec(&serde_json::json!({})).unwrap())
                .is_empty()
        );
    }

    #[test]
    fn a_malformed_entry_is_dropped_rather_than_half_read() {
        let config = rmp_serde::to_vec(&serde_json::json!({
            FOREIGN_ENVIRONMENTS_CONFIG_KEY: {
                "typescript": { "modules": { "./util": { "integrity": "sha256-aa" } } }
            }
        }))
        .expect("encodes");
        let modules = LockedModules::from_config(&config);
        assert!(
            modules.resolve("./util").is_err(),
            "an entry with no path must refuse at the import, not load a guessed path"
        );
    }
}

// ============================================================================
// The deno_core loader
// ============================================================================

/// Resolves and loads imports for a `fn typescript` body, from the lock only.
///
/// The specifier is carried through resolution as an opaque `shape-locked:`
/// URL rather than being turned into a `file://` path: V8 requires resolution
/// to produce a URL, and a `file://` URL would let the ordinary relative-URL
/// algorithm join a nested import against a vendored file's directory — which
/// is a filesystem walk, arrived at by accident. Keeping the specifier itself
/// in the URL means every import, nested or not, goes back through the table.
pub struct LockfileModuleLoader {
    modules: LockedModules,
}

impl LockfileModuleLoader {
    pub fn new(modules: LockedModules) -> Self {
        Self { modules }
    }

    /// The URL scheme resolution produces. Not a real transport — the loader is
    /// the only thing that ever reads it.
    const SCHEME: &'static str = "shape-locked";

    fn specifier_of(url: &deno_core::ModuleSpecifier) -> String {
        url.path().to_string()
    }
}

impl deno_core::ModuleLoader for LockfileModuleLoader {
    fn resolve(
        &self,
        specifier: &str,
        _referrer: &str,
        _kind: deno_core::ResolutionKind,
    ) -> Result<deno_core::ModuleSpecifier, deno_core::error::AnyError> {
        // Refuse at resolve, not at load: an unlocked import must never become
        // a URL that something downstream might try to fetch.
        self.modules.resolve(specifier)?;
        deno_core::ModuleSpecifier::parse(&format!("{}:{specifier}", Self::SCHEME)).map_err(|e| {
            deno_core::error::AnyError::from(ModuleRefusal::Unreadable {
                path: specifier.to_string(),
                detail: e.to_string(),
            })
        })
    }

    fn load(
        &self,
        module_specifier: &deno_core::ModuleSpecifier,
        _maybe_referrer: Option<&deno_core::ModuleSpecifier>,
        _is_dyn_import: bool,
        _requested_module_type: deno_core::RequestedModuleType,
    ) -> deno_core::ModuleLoadResponse {
        let specifier = Self::specifier_of(module_specifier);
        let outcome = self
            .modules
            .resolve(&specifier)
            .and_then(|locked| self.modules.read(locked))
            .map(|source| {
                deno_core::ModuleSource::new(
                    deno_core::ModuleType::JavaScript,
                    deno_core::ModuleSourceCode::String(source.into()),
                    module_specifier,
                    None,
                )
            })
            .map_err(deno_core::error::AnyError::from);
        deno_core::ModuleLoadResponse::Sync(outcome)
    }
}
