//! `.d.ts` generation from a declared Shape contract.
//!
//! ADR-019 §1 / R25 (POLY-STUB-CHANNEL, issue #196).
//!
//! The host classifies Shape type spellings into `ForeignType` (the marshaling
//! table in `shape-abi-v1`) and delivers them through `register_types`; this
//! module turns that into TypeScript. Nothing here parses a Shape type, and
//! nothing on the host renders a TypeScript one.
//!
//! # `int` and `number`
//!
//! Shape distinguishes `int` (i64) from `number` (f64); TypeScript has one
//! numeric type. Rendering both as `number` would erase a declared distinction
//! and make the stub unable to describe the contract it was generated from, so
//! `int` renders as the emitted alias `ShapeInt`. The alias is structurally
//! `number` — tsc will not enforce integrality — but it keeps the declaration
//! readable and carries the i64 range caveat where an author will see it.

use shape_abi_v1::foreign_types::{ForeignContractExport, ForeignScalar, ForeignType};

/// The alias name emitted for Shape's `int`.
pub const SHAPE_INT: &str = "ShapeInt";

/// Render the `.d.ts` stub document for a declared contract.
pub fn render_stub(contract: &ForeignContractExport) -> String {
    let mut out = String::new();
    out.push_str("// Generated by the Shape TypeScript runtime extension — do not edit.\n");
    out.push_str("// Interface declarations for the declared Shape contract (ADR-019 §1).\n\n");
    out.push_str("/** Shape `int` (i64). Structurally a `number`: values beyond 2^53 lose\n");
    out.push_str(" *  precision crossing the boundary. */\n");
    out.push_str(&format!("type {SHAPE_INT} = number;\n\n"));

    let mut anon = AnonNames::default();

    for ty in &contract.types {
        render_object_declaration(ty, &mut anon, &mut out);
    }

    for function in &contract.functions {
        for param in &function.params {
            declare_inline_objects(&param.ty, &mut anon, &mut out);
        }
        declare_inline_objects(&function.returns, &mut anon, &mut out);
    }

    for function in &contract.functions {
        let params: Vec<String> = function
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, ts_type(&p.ty, &anon)))
            .collect();
        out.push_str(&format!(
            "declare function {}({}): {};\n",
            function.name,
            params.join(", "),
            ts_type(&function.returns, &anon)
        ));
    }

    out
}

/// Names assigned to inline object literals, keyed by their Shape spelling so
/// one literal shape gets one interface however often it appears.
#[derive(Default)]
pub struct AnonNames {
    entries: Vec<(String, String)>,
}

impl AnonNames {
    fn name_for(&mut self, spelling: &str) -> (String, bool) {
        if let Some((_, name)) = self.entries.iter().find(|(s, _)| s == spelling) {
            return (name.clone(), false);
        }
        let name = format!("ShapeObject{}", self.entries.len() + 1);
        self.entries.push((spelling.to_string(), name.clone()));
        (name, true)
    }

    fn lookup(&self, spelling: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(s, _)| s == spelling)
            .map(|(_, n)| n.as_str())
    }
}

fn render_object_declaration(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    let ForeignType::Object { name, fields } = ty else {
        return;
    };
    let interface_name = match name {
        Some(n) => n.clone(),
        None => anon.name_for(&ty.shape_spelling()).0,
    };
    match fields {
        Some(fields) if !fields.is_empty() => {
            out.push_str(&format!("interface {interface_name} {{\n"));
            for field in fields {
                let optional = if field.optional { "?" } else { "" };
                out.push_str(&format!(
                    "  {}{}: {};\n",
                    field.name,
                    optional,
                    ts_type(&field.ty, anon)
                ));
            }
            out.push_str("}\n\n");
        }
        _ => {
            // A type whose fields the host could not export. An empty interface
            // in TypeScript accepts anything, which would be a lie about the
            // contract; the index signature says "unknown fields" honestly.
            out.push_str(&format!(
                "/** Fields not exported: this Shape type has a field whose type has no \
                 wire form. */\ninterface {interface_name} {{\n  [key: string]: unknown;\n}}\n\n"
            ));
        }
    }
}

fn declare_inline_objects(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    match ty {
        ForeignType::Optional(inner) => declare_inline_objects(inner, anon, out),
        ForeignType::Object { name: None, .. } => {
            let (_, is_new) = anon.name_for(&ty.shape_spelling());
            if is_new {
                render_inline_object(ty, anon, out);
            }
        }
        _ => {}
    }
}

fn render_inline_object(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    let ForeignType::Object { fields, .. } = ty else {
        return;
    };
    let interface_name = anon
        .lookup(&ty.shape_spelling())
        .expect("the name was reserved before rendering")
        .to_string();
    out.push_str(&format!("interface {interface_name} {{\n"));
    if let Some(fields) = fields {
        for field in fields {
            let optional = if field.optional { "?" } else { "" };
            out.push_str(&format!(
                "  {}{}: {};\n",
                field.name,
                optional,
                ts_type(&field.ty, anon)
            ));
        }
    }
    out.push_str("}\n\n");
}

/// The TypeScript type for a table entry.
///
/// Matched exhaustively: a new `ForeignType` constructor cannot land without a
/// TypeScript rendering, which is half of the per-type stub coverage guarantee
/// (the other half is `render_round_trips_every_table_entry`).
pub fn ts_type(ty: &ForeignType, anon: &AnonNames) -> String {
    match ty {
        ForeignType::Scalar(s) => ts_scalar(*s).to_string(),
        ForeignType::Array(s) => format!("{}[]", ts_scalar(*s)),
        ForeignType::Map(s) => format!("Record<string, {}>", ts_scalar(*s)),
        ForeignType::Optional(inner) => format!("{} | null", ts_type(inner, anon)),
        ForeignType::Object { name: Some(n), .. } => n.clone(),
        ForeignType::Object { name: None, .. } => anon
            .lookup(&ty.shape_spelling())
            .unwrap_or("object")
            .to_string(),
    }
}

fn ts_scalar(scalar: ForeignScalar) -> &'static str {
    match scalar {
        ForeignScalar::Int => SHAPE_INT,
        ForeignScalar::Number => "number",
        ForeignScalar::Bool => "boolean",
        ForeignScalar::String => "string",
        // MessagePack nil arrives as `null`, not `undefined`.
        ForeignScalar::Unit => "null",
    }
}

/// The inverse of [`ts_type`]: recover the canonical Shape spelling from a
/// rendered TypeScript type.
///
/// Exists so the mapping can be asserted to round-trip per table entry rather
/// than merely to exist. It is also what forced `ShapeInt`: without it, `int`
/// and `number` would both render as `number` and the contract would not be
/// recoverable from its own stub.
pub fn shape_spelling_of_ts_type(rendered: &str) -> Option<String> {
    let rendered = rendered.trim();
    if let Some(head) = rendered.strip_suffix("| null") {
        let inner = shape_spelling_of_ts_type(head.trim_end())?;
        return Some(format!("Option<{inner}>"));
    }
    if let Some(head) = rendered.strip_suffix("[]") {
        let inner = shape_spelling_of_ts_type(head)?;
        return Some(format!("Array<{inner}>"));
    }
    if let Some(rest) = rendered.strip_prefix("Record<string, ") {
        let inner = shape_spelling_of_ts_type(rest.strip_suffix('>')?)?;
        return Some(format!("HashMap<string, {inner}>"));
    }
    match rendered {
        SHAPE_INT => Some("int".to_string()),
        "number" => Some("number".to_string()),
        "boolean" => Some("bool".to_string()),
        "string" => Some("string".to_string()),
        "null" => Some("none".to_string()),
        name if is_identifier(name) => Some(name.to_string()),
        _ => None,
    }
}

fn is_identifier(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .next()
            .is_some_and(|c| c.is_alphabetic() || c == '_')
        && s.chars().all(|c| c.is_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use shape_abi_v1::foreign_types::{
        ForeignDirection, ForeignField, ForeignFunctionContract, ForeignParamContract, ForeignType,
        marshal_table,
    };

    /// ADR-019 §1 / #196 tripwire (1), TypeScript side: every type in the
    /// marshaling table has a `.d.ts` rendering, and that rendering carries
    /// enough information to recover the Shape type it came from — asserted per
    /// type, over a table the host generates mechanically, so a new marshal type
    /// with no stub mapping fails here.
    #[test]
    fn render_round_trips_every_table_entry() {
        let anon = AnonNames::default();
        for entry in marshal_table() {
            let rendered = ts_type(&entry, &anon);
            let recovered = shape_spelling_of_ts_type(&rendered).unwrap_or_else(|| {
                panic!(
                    "table entry `{}` rendered as `{}`, which maps back to no Shape type",
                    entry.shape_spelling(),
                    rendered
                )
            });
            assert_eq!(
                recovered,
                entry.shape_spelling(),
                "table entry `{}` rendered as `{}` and came back as `{}`",
                entry.shape_spelling(),
                rendered,
                recovered
            );
            let direction = if entry.supports(ForeignDirection::Return) {
                ForeignDirection::Return
            } else {
                ForeignDirection::Argument
            };
            ForeignType::classify(&recovered, direction).unwrap_or_else(|e| {
                panic!("recovered spelling `{recovered}` is not classifiable: {e:?}")
            });
        }
    }

    /// The reason `ShapeInt` exists. If a future edit collapses it to `number`,
    /// this fails before the round-trip test does, naming the cause.
    #[test]
    fn int_and_number_render_distinguishably() {
        let anon = AnonNames::default();
        let int = ts_type(&ForeignType::Scalar(ForeignScalar::Int), &anon);
        let number = ts_type(&ForeignType::Scalar(ForeignScalar::Number), &anon);
        assert_ne!(
            int, number,
            "Shape distinguishes int from number; a stub that renders both as \
             `number` cannot describe the contract it came from"
        );
        assert_eq!(int, SHAPE_INT);
    }

    #[test]
    fn every_scalar_has_a_distinct_ts_rendering() {
        let anon = AnonNames::default();
        let mut seen: Vec<String> = Vec::new();
        for scalar in ForeignScalar::ALL {
            let rendered = ts_type(&ForeignType::Scalar(*scalar), &anon);
            assert!(
                !seen.contains(&rendered),
                "scalar {scalar:?} shares the rendering `{rendered}` with another scalar \
                 — the mapping would not be invertible"
            );
            seen.push(rendered);
        }
    }

    fn contract_with(
        functions: Vec<ForeignFunctionContract>,
        types: Vec<ForeignType>,
    ) -> ForeignContractExport {
        let mut contract = ForeignContractExport::new("typescript");
        contract.functions = functions;
        contract.types = types;
        contract
    }

    #[test]
    fn a_declared_function_becomes_a_declare_function() {
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "add".to_string(),
                params: vec![
                    ForeignParamContract {
                        name: "a".to_string(),
                        ty: ForeignType::Scalar(ForeignScalar::Int),
                    },
                    ForeignParamContract {
                        name: "xs".to_string(),
                        ty: ForeignType::Array(ForeignScalar::Number),
                    },
                ],
                returns: ForeignType::Scalar(ForeignScalar::Int),
            }],
            Vec::new(),
        );
        let stub = render_stub(&contract);
        assert!(
            stub.contains("declare function add(a: ShapeInt, xs: number[]): ShapeInt;"),
            "got:\n{stub}"
        );
        assert!(
            stub.contains("type ShapeInt = number;"),
            "the alias must be declared before use:\n{stub}"
        );
    }

    #[test]
    fn a_named_object_type_becomes_an_interface() {
        let candle = ForeignType::Object {
            name: Some("Candle".to_string()),
            fields: Some(vec![
                ForeignField {
                    name: "open".to_string(),
                    ty: ForeignType::Scalar(ForeignScalar::Number),
                    optional: false,
                },
                ForeignField {
                    name: "label".to_string(),
                    ty: ForeignType::Scalar(ForeignScalar::String),
                    optional: true,
                },
            ]),
        };
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "analyze".to_string(),
                params: vec![ForeignParamContract {
                    name: "c".to_string(),
                    ty: ForeignType::Object {
                        name: Some("Candle".to_string()),
                        fields: None,
                    },
                }],
                returns: ForeignType::Scalar(ForeignScalar::Number),
            }],
            vec![candle],
        );
        let stub = render_stub(&contract);
        assert!(stub.contains("interface Candle {"), "got:\n{stub}");
        assert!(stub.contains("  open: number;"), "got:\n{stub}");
        assert!(stub.contains("  label?: string;"), "got:\n{stub}");
        assert!(
            stub.contains("declare function analyze(c: Candle): number;"),
            "got:\n{stub}"
        );
        assert!(
            stub.find("interface Candle").unwrap() < stub.find("declare function").unwrap(),
            "the interface must be declared before the function that uses it:\n{stub}"
        );
    }

    #[test]
    fn a_type_whose_fields_were_not_exported_says_so() {
        let contract = contract_with(
            Vec::new(),
            vec![ForeignType::Object {
                name: Some("Bag".to_string()),
                fields: None,
            }],
        );
        let stub = render_stub(&contract);
        assert!(stub.contains("interface Bag {"), "got:\n{stub}");
        assert!(
            stub.contains("Fields not exported"),
            "an unexportable type must be labelled:\n{stub}"
        );
        assert!(
            stub.contains("[key: string]: unknown;"),
            "an empty TS interface accepts anything — say `unknown` instead:\n{stub}"
        );
    }

    #[test]
    fn an_inline_object_literal_gets_a_declared_name_before_use() {
        let literal = ForeignType::Object {
            name: None,
            fields: Some(vec![ForeignField {
                name: "value".to_string(),
                ty: ForeignType::Scalar(ForeignScalar::Number),
                optional: false,
            }]),
        };
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "measure".to_string(),
                params: Vec::new(),
                returns: literal,
            }],
            Vec::new(),
        );
        let stub = render_stub(&contract);
        assert!(stub.contains("interface ShapeObject1 {"), "got:\n{stub}");
        assert!(stub.contains("  value: number;"), "got:\n{stub}");
        assert!(
            stub.contains("declare function measure(): ShapeObject1;"),
            "got:\n{stub}"
        );
    }
}
