//! FFI function references for JIT-compiled code.
//!
//! `FFIFuncRefs` holds Cranelift `FuncRef` handles for every FFI helper
//! that JIT-generated IR can call. Extracted from `translator::types` so
//! that non-translator code (compiler, optimizer, mir_compiler) can depend
//! on it without pulling in the full translator module.

use cranelift::codegen::ir::FuncRef;

/// FFI function references for heap operations
#[allow(dead_code)]
pub struct FFIFuncRefs {
    pub(crate) new_array: FuncRef,
    pub(crate) new_object: FuncRef,
    pub(crate) get_prop: FuncRef,
    pub(crate) set_prop: FuncRef,
    pub(crate) length: FuncRef,
    pub(crate) array_get: FuncRef,
    pub(crate) call_function: FuncRef,
    pub(crate) call_value: FuncRef,
    pub(crate) call_foreign: FuncRef,
    pub(crate) call_foreign_native: FuncRef,
    pub(crate) call_foreign_dynamic: FuncRef,
    pub(crate) call_foreign_native_0: FuncRef,
    pub(crate) call_foreign_native_1: FuncRef,
    pub(crate) call_foreign_native_2: FuncRef,
    pub(crate) call_foreign_native_3: FuncRef,
    pub(crate) call_foreign_native_4: FuncRef,
    pub(crate) call_foreign_native_5: FuncRef,
    pub(crate) call_foreign_native_6: FuncRef,
    pub(crate) call_foreign_native_7: FuncRef,
    pub(crate) call_foreign_native_8: FuncRef,
    pub(crate) iter_next: FuncRef,
    pub(crate) iter_done: FuncRef,
    pub(crate) call_method: FuncRef,
    pub(crate) type_of: FuncRef,
    pub(crate) type_check: FuncRef,
    // Result type operations (Ok/Err)
    pub(crate) make_ok: FuncRef,
    pub(crate) make_err: FuncRef,
    pub(crate) is_ok: FuncRef,
    pub(crate) is_err: FuncRef,
    pub(crate) is_result: FuncRef,
    pub(crate) unwrap_ok: FuncRef,
    pub(crate) unwrap_err: FuncRef,
    pub(crate) unwrap_or: FuncRef,
    pub(crate) result_inner: FuncRef,
    // Option type operations (Some/None)
    pub(crate) make_some: FuncRef,
    pub(crate) is_some: FuncRef,
    pub(crate) is_none: FuncRef,
    pub(crate) unwrap_some: FuncRef,
    pub(crate) array_first: FuncRef,
    pub(crate) array_last: FuncRef,
    pub(crate) array_min: FuncRef,
    pub(crate) array_max: FuncRef,
    pub(crate) slice: FuncRef,
    pub(crate) range: FuncRef,
    pub(crate) make_range: FuncRef,
    pub(crate) to_string: FuncRef,
    pub(crate) to_number: FuncRef,
    pub(crate) print: FuncRef,
    pub(crate) sin: FuncRef,
    pub(crate) cos: FuncRef,
    pub(crate) tan: FuncRef,
    pub(crate) asin: FuncRef,
    pub(crate) acos: FuncRef,
    pub(crate) atan: FuncRef,
    pub(crate) exp: FuncRef,
    pub(crate) ln: FuncRef,
    pub(crate) log: FuncRef,
    pub(crate) pow: FuncRef,
    pub(crate) control_fold: FuncRef,
    pub(crate) control_reduce: FuncRef,
    pub(crate) control_map: FuncRef,
    pub(crate) control_filter: FuncRef,
    pub(crate) control_foreach: FuncRef,
    pub(crate) control_find: FuncRef,
    pub(crate) control_find_index: FuncRef,
    pub(crate) control_some: FuncRef,
    pub(crate) control_every: FuncRef,
    pub(crate) array_push: FuncRef,
    pub(crate) array_pop: FuncRef,
    pub(crate) array_push_elem: FuncRef,
    pub(crate) array_push_local: FuncRef,
    pub(crate) array_reserve_local: FuncRef,
    pub(crate) array_zip: FuncRef,
    pub(crate) array_filled: FuncRef,
    pub(crate) array_reverse: FuncRef,
    pub(crate) array_push_element: FuncRef,
    pub(crate) make_closure: FuncRef,
    pub(crate) eval_datetime_expr: FuncRef,
    pub(crate) eval_time_reference: FuncRef,
    pub(crate) eval_data_datetime_ref: FuncRef,
    pub(crate) eval_data_relative: FuncRef,
    pub(crate) intrinsic_series: FuncRef,
    pub(crate) series_method: FuncRef,
    pub(crate) format_error: FuncRef,
    pub(crate) object_rest: FuncRef,
    pub(crate) format: FuncRef,
    pub(crate) generic_add: FuncRef,
    pub(crate) generic_sub: FuncRef,
    pub(crate) generic_mul: FuncRef,
    pub(crate) generic_div: FuncRef,
    pub(crate) generic_eq: FuncRef,
    pub(crate) generic_neq: FuncRef,
    pub(crate) series_shift: FuncRef,
    pub(crate) series_fillna: FuncRef,
    pub(crate) series_rolling_mean: FuncRef,
    pub(crate) series_rolling_sum: FuncRef,
    pub(crate) series_rolling_std: FuncRef,
    pub(crate) intrinsic_rolling_std: FuncRef,
    pub(crate) series_cumsum: FuncRef,
    pub(crate) series_gt: FuncRef,
    pub(crate) series_lt: FuncRef,
    pub(crate) series_gte: FuncRef,
    pub(crate) series_lte: FuncRef,
    pub(crate) intrinsic_sum: FuncRef,
    pub(crate) intrinsic_mean: FuncRef,
    pub(crate) intrinsic_min: FuncRef,
    pub(crate) intrinsic_max: FuncRef,
    pub(crate) intrinsic_std: FuncRef,
    pub(crate) intrinsic_variance: FuncRef,
    pub(crate) intrinsic_median: FuncRef,
    pub(crate) intrinsic_percentile: FuncRef,
    pub(crate) intrinsic_correlation: FuncRef,
    pub(crate) intrinsic_covariance: FuncRef,
    // Vector intrinsics (boxed interface - legacy)
    pub(crate) intrinsic_vec_abs: FuncRef,
    pub(crate) intrinsic_vec_sqrt: FuncRef,
    pub(crate) intrinsic_vec_ln: FuncRef,
    pub(crate) intrinsic_vec_exp: FuncRef,
    pub(crate) intrinsic_vec_add: FuncRef,
    pub(crate) intrinsic_vec_sub: FuncRef,
    pub(crate) intrinsic_vec_mul: FuncRef,
    pub(crate) intrinsic_vec_div: FuncRef,
    pub(crate) intrinsic_vec_max: FuncRef,
    pub(crate) intrinsic_vec_min: FuncRef,
    pub(crate) intrinsic_matmul_vec: FuncRef,
    pub(crate) intrinsic_matmul_mat: FuncRef,

    // Raw pointer SIMD operations (zero-copy, high performance)
    // Binary: simd_op(ptr_a, ptr_b, len) -> result_ptr
    pub(crate) simd_add: FuncRef,
    pub(crate) simd_sub: FuncRef,
    pub(crate) simd_mul: FuncRef,
    pub(crate) simd_div: FuncRef,
    pub(crate) simd_max: FuncRef,
    pub(crate) simd_min: FuncRef,
    // Scalar broadcast: simd_op_scalar(ptr, scalar, len) -> result_ptr
    pub(crate) simd_add_scalar: FuncRef,
    pub(crate) simd_sub_scalar: FuncRef,
    pub(crate) simd_mul_scalar: FuncRef,
    pub(crate) simd_div_scalar: FuncRef,
    // Comparison: simd_cmp(ptr_a, ptr_b, len) -> mask_ptr (1.0/0.0)
    pub(crate) simd_gt: FuncRef,
    pub(crate) simd_lt: FuncRef,
    pub(crate) simd_gte: FuncRef,
    pub(crate) simd_lte: FuncRef,
    pub(crate) simd_eq: FuncRef,
    pub(crate) simd_neq: FuncRef,
    // Memory management
    pub(crate) simd_free: FuncRef,

    pub(crate) series_rolling_min: FuncRef,
    pub(crate) series_rolling_max: FuncRef,
    pub(crate) series_ema: FuncRef,
    pub(crate) series_diff: FuncRef,
    pub(crate) series_pct_change: FuncRef,
    pub(crate) series_cumprod: FuncRef,
    pub(crate) series_clip: FuncRef,
    pub(crate) series_broadcast: FuncRef,
    pub(crate) series_highest_index: FuncRef,
    pub(crate) series_lowest_index: FuncRef,
    pub(crate) time_current_time: FuncRef,
    pub(crate) time_symbol: FuncRef,
    pub(crate) time_last_row: FuncRef,
    pub(crate) time_range: FuncRef,
    pub(crate) get_all_rows: FuncRef,
    pub(crate) align_series: FuncRef,
    pub(crate) run_simulation: FuncRef,
    // Generic DataFrame access (industry-agnostic)
    pub(crate) get_field: FuncRef,
    pub(crate) get_row_ref: FuncRef,
    pub(crate) row_get_field: FuncRef,
    pub(crate) get_row_timestamp: FuncRef,
    // Type-specialized field access (JIT optimization)
    pub(crate) get_field_typed: FuncRef,
    pub(crate) set_field_typed: FuncRef,
    // TypedObject allocation
    pub(crate) typed_object_alloc: FuncRef,
    // TypedObject merge (O(1) memcpy-based)
    pub(crate) typed_merge_object: FuncRef,
    // Typed column access (Arrow-backed LoadCol* opcodes)
    pub(crate) load_col_f64: FuncRef,
    pub(crate) load_col_i64: FuncRef,
    pub(crate) load_col_bool: FuncRef,
    pub(crate) load_col_str: FuncRef,
    // GC safepoint poll (called at loop headers)
    pub(crate) gc_safepoint: FuncRef,
    // Reference operations
    pub(crate) set_index_ref: FuncRef,
    // Array info (data_ptr, length) extraction via stable Rust API
    pub(crate) array_info: FuncRef,
    // HOF inlining array operations
    pub(crate) hof_array_alloc: FuncRef,
    pub(crate) hof_array_push: FuncRef,
    // Async task operations
    pub(crate) spawn_task: FuncRef,
    pub(crate) join_init: FuncRef,
    pub(crate) join_await: FuncRef,
    pub(crate) cancel_task: FuncRef,
    pub(crate) async_scope_enter: FuncRef,
    pub(crate) async_scope_exit: FuncRef,
    // Shape guard operations (HashMap hidden class)
    pub(crate) hashmap_shape_id: FuncRef,
    pub(crate) hashmap_value_at: FuncRef,
    // Generic builtin trampoline (handles any builtin not lowered by dedicated JIT paths)
    pub(crate) generic_builtin: FuncRef,
}
