#!/usr/bin/env bash
# create-agent-worktree.sh — Hardening (4) Option B per-worktree creation
# with PATH-wrapper .envrc shim.
#
# Authorized by supervisor 2026-05-28 after 4 stash-binding violations
# (LSP-B, LSP-C, joint-fix-1a, c2-A — all hook-gap pattern; the
# previously-deployed hardening (4) wrapper at 53549fcb required
# per-Bash-call PATH-export by the agent, which broke at agent
# compliance under the Claude Code Bash tool's fresh-shell-per-call
# semantics).
#
# This script bundles worktree creation + wrapper install + .envrc shim
# write + direnv allow so the wrapper is mechanically enforced via
# direnv shell hooks — agents do NOT touch the .envrc.
#
# Usage:
#   scripts/create-agent-worktree.sh <branch-name> [<base-ref>]
#
# Example:
#   scripts/create-agent-worktree.sh c5-b-bitwise-gate HEAD
#
# Output:
#   /home/dev/dev/shape-lang/shape-<branch> with .envrc + direnv allowed
#   /tmp/shape-<branch>-bin/git wrapper installed
#
# Per supervisor 2026-05-28 binders:
#   (1) Q3-on-self empirically verified at first deployment 2026-05-28
#       (5/5 tests green; direnv source_up + PATH_add + auto-load via
#       `eval $(direnv export bash)` confirmed).
#   (2) Setup-time mechanical — this script IS that mechanism.
#   (3) Pre-flight discipline preserved — dispatch prompts MUST still
#       have agents verify `which git` resolves to wrapper as first
#       action + REFUSE TO PROCEED if not.
#   (4) Hardening 3 pre-commit hook + Hardening 2 dispatch-template
#       forbid-line preserved as defense-in-depth.

set -euo pipefail

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "usage: $0 <branch-name> [<base-ref>]" >&2
    exit 2
fi

BRANCH="$1"
BASE_REF="${2:-HEAD}"
WORKTREE_DIR="/home/dev/dev/shape-lang/shape-${BRANCH}"
BINDIR="/tmp/shape-${BRANCH}-bin"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHAPE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Step 1: Create the worktree
echo "Step 1: create worktree at $WORKTREE_DIR (branch $BRANCH, base $BASE_REF)"
git -C "$SHAPE_DIR" worktree add "$WORKTREE_DIR" -b "$BRANCH" "$BASE_REF"

# Step 2: Install the git-stash wrapper in the per-branch bindir
echo "Step 2: install git-stash wrapper at $BINDIR/git"
bash "$SCRIPT_DIR/install-git-stash-wrapper.sh" "$BRANCH"

# Step 3: Write the .envrc shim into the worktree
echo "Step 3: write .envrc shim into worktree"
cat > "$WORKTREE_DIR/.envrc" <<EOF
# Hardening (4) Option B — per-worktree git-stash PATH wrapper.
# Auto-generated by scripts/create-agent-worktree.sh on $(date +%Y-%m-%d).
# Authorized by supervisor 2026-05-28 (4 stash-binding incident pattern).
#
# This .envrc:
#   (1) sources the parent devenv .envrc (devenv shell + Rust toolchain
#       per CLAUDE.md "cargo/build/gate commands must run via direnv exec")
#   (2) PATH-prepends the per-worktree wrapper bindir so 'git stash' is
#       intercepted in every shell that enters this worktree
#
# direnv hooks load this on cd into the worktree; agents activate via
# 'eval \$(direnv export bash)' as their first action.
# Agents do NOT touch this .envrc.

source_up

PATH_add "$BINDIR"
EOF

# Step 4: direnv allow the .envrc (required for direnv to actually load it)
echo "Step 4: direnv allow $WORKTREE_DIR/.envrc"
direnv allow "$WORKTREE_DIR"

# Step 5: Sanity-check the wrapper resolution
echo "Step 5: sanity check"
if [ ! -x "$BINDIR/git" ]; then
    echo "ERROR: wrapper not executable at $BINDIR/git" >&2
    exit 3
fi
if ! grep -q "PATH_add \"$BINDIR\"" "$WORKTREE_DIR/.envrc"; then
    echo "ERROR: .envrc missing PATH_add line for $BINDIR" >&2
    exit 4
fi

echo
echo "═══════════════════════════════════════════════════════════════════════"
echo "Worktree ready for agent dispatch:"
echo "  path:     $WORKTREE_DIR"
echo "  branch:   $BRANCH"
echo "  base:     $BASE_REF"
echo "  wrapper:  $BINDIR/git"
echo "  .envrc:   $WORKTREE_DIR/.envrc (direnv allowed)"
echo
echo "Agent's first action MUST be:"
echo "  cd $WORKTREE_DIR"
echo "  eval \"\$(direnv export bash 2>/dev/null)\""
echo "  which git    # must print: $BINDIR/git"
echo "═══════════════════════════════════════════════════════════════════════"
