//! Shape Python language runtime extension.
//!
//! Provides a `shape.language_runtime` capability that embeds CPython
//! for executing `foreign "python" { ... }` blocks in Shape programs.
//!
//! # ABI Exports
//!
//! All C ABI exports (`shape_plugin_info`, `shape_abi_version`,
//! `shape_capability_manifest`, `shape_capability_vtable`,
//! `shape_language_runtime_vtable`) are generated by the
//! [`shape_abi_v1::language_runtime_plugin!`] macro below.

pub mod arrow_bridge;
pub mod error_mapping;
pub mod marshaling;
pub mod runtime;

shape_abi_v1::language_runtime_plugin! {
    name: c"python",
    version: c"0.1.0",
    description: c"Python language runtime for foreign function blocks",
    vtable: {
        init: runtime::python_init,
        register_types: runtime::python_register_types,
        compile: runtime::python_compile,
        invoke: runtime::python_invoke,
        dispose_function: runtime::python_dispose_function,
        language_id: runtime::python_language_id,
        get_lsp_config: runtime::python_get_lsp_config,
        free_buffer: runtime::python_free_buffer,
        drop: runtime::python_drop,
    }
}
