//! `.pyi` generation from a declared Shape contract.
//!
//! ADR-019 §1 / R25 (POLY-STUB-CHANNEL, issue #196).
//!
//! The host classifies Shape type spellings into `ForeignType` (the marshaling
//! table in `shape-abi-v1`) and delivers them through `register_types`; this
//! module turns that into Python. Nothing here parses a Shape type, and nothing
//! on the host renders a Python one.
//!
//! Objects are `TypedDict`s, not dataclasses: a Shape object crosses as a
//! MessagePack map and arrives in the body as a `dict`, so a `TypedDict` is
//! what the body actually receives. Saying `@dataclass` would type-check code
//! that fails at runtime.

use shape_abi_v1::foreign_types::{ForeignContractExport, ForeignScalar, ForeignType};

/// Render the `.pyi` stub document for a declared contract.
pub fn render_stub(contract: &ForeignContractExport) -> String {
    let mut out = String::new();
    out.push_str("# Generated by the Shape Python runtime extension — do not edit.\n");
    out.push_str("# Interface stubs for the declared Shape contract (ADR-019 §1).\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from typing import TypedDict\n\n");

    let mut anon = AnonNames::default();

    for ty in &contract.types {
        render_object_declaration(ty, &mut anon, &mut out);
    }

    // Inline object literals in signatures need a name before they are used.
    for function in &contract.functions {
        for param in &function.params {
            declare_inline_objects(&param.ty, &mut anon, &mut out);
        }
        declare_inline_objects(&function.returns, &mut anon, &mut out);
    }

    for function in &contract.functions {
        let params: Vec<String> = function
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, python_type(&p.ty, &anon)))
            .collect();
        out.push_str(&format!(
            "def {}({}) -> {}: ...\n",
            function.name,
            params.join(", "),
            python_type(&function.returns, &anon)
        ));
    }

    out
}

/// Names assigned to inline object literals, keyed by their Shape spelling so
/// one literal shape gets one class however often it appears.
#[derive(Default)]
pub struct AnonNames {
    entries: Vec<(String, String)>,
}

impl AnonNames {
    fn name_for(&mut self, spelling: &str) -> (String, bool) {
        if let Some((_, name)) = self.entries.iter().find(|(s, _)| s == spelling) {
            return (name.clone(), false);
        }
        let name = format!("_ShapeObject{}", self.entries.len() + 1);
        self.entries.push((spelling.to_string(), name.clone()));
        (name, true)
    }

    fn lookup(&self, spelling: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(s, _)| s == spelling)
            .map(|(_, n)| n.as_str())
    }
}

fn render_object_declaration(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    let ForeignType::Object { name, fields } = ty else {
        return;
    };
    let class_name = match name {
        Some(n) => n.clone(),
        None => anon.name_for(&ty.shape_spelling()).0,
    };
    match fields {
        Some(fields) if !fields.is_empty() => {
            out.push_str(&format!("class {class_name}(TypedDict):\n"));
            for field in fields {
                out.push_str(&format!(
                    "    {}: {}\n",
                    field.name,
                    python_type(&field.ty, anon)
                ));
            }
            out.push('\n');
        }
        _ => {
            // A type whose fields the host could not export — say so rather
            // than emit an empty TypedDict that would type-check away real
            // field accesses.
            out.push_str(&format!(
                "class {class_name}(TypedDict, total=False):\n    \
                 # fields not exported: this Shape type has a field whose type \
                 has no wire form\n    pass\n\n"
            ));
        }
    }
}

fn declare_inline_objects(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    match ty {
        ForeignType::Optional(inner) => declare_inline_objects(inner, anon, out),
        ForeignType::Object { name: None, .. } => {
            let (_, is_new) = anon.name_for(&ty.shape_spelling());
            if is_new {
                // `name_for` already reserved the name; render with it.
                render_inline_object(ty, anon, out);
            }
        }
        _ => {}
    }
}

fn render_inline_object(ty: &ForeignType, anon: &mut AnonNames, out: &mut String) {
    let ForeignType::Object { fields, .. } = ty else {
        return;
    };
    let class_name = anon
        .lookup(&ty.shape_spelling())
        .expect("the name was reserved before rendering")
        .to_string();
    out.push_str(&format!("class {class_name}(TypedDict):\n"));
    match fields {
        Some(fields) if !fields.is_empty() => {
            for field in fields {
                out.push_str(&format!(
                    "    {}: {}\n",
                    field.name,
                    python_type(&field.ty, anon)
                ));
            }
        }
        _ => out.push_str("    pass\n"),
    }
    out.push('\n');
}

/// The Python type for a table entry.
///
/// Matched exhaustively: a new `ForeignType` constructor cannot land without a
/// Python rendering, which is half of the per-type stub coverage guarantee (the
/// other half is `render_round_trips_every_table_entry`).
pub fn python_type(ty: &ForeignType, anon: &AnonNames) -> String {
    match ty {
        ForeignType::Scalar(s) => python_scalar(*s).to_string(),
        ForeignType::Array(s) => format!("list[{}]", python_scalar(*s)),
        ForeignType::Map(s) => format!("dict[str, {}]", python_scalar(*s)),
        ForeignType::Optional(inner) => format!("{} | None", python_type(inner, anon)),
        ForeignType::Object { name: Some(n), .. } => n.clone(),
        ForeignType::Object { name: None, .. } => anon
            .lookup(&ty.shape_spelling())
            .unwrap_or("dict")
            .to_string(),
    }
}

fn python_scalar(scalar: ForeignScalar) -> &'static str {
    match scalar {
        ForeignScalar::Int => "int",
        ForeignScalar::Number => "float",
        ForeignScalar::Bool => "bool",
        ForeignScalar::String => "str",
        ForeignScalar::Unit => "None",
    }
}

/// The inverse of [`python_type`]: recover the canonical Shape spelling from a
/// rendered Python hint.
///
/// Exists so the mapping can be asserted to round-trip per table entry rather
/// than merely to exist. A mapping that cannot be inverted is one that has lost
/// information about the declared contract.
pub fn shape_spelling_of_python_type(hint: &str) -> Option<String> {
    let hint = hint.trim();
    if let Some(head) = hint.strip_suffix("| None") {
        let inner = shape_spelling_of_python_type(head.trim_end())?;
        return Some(format!("Option<{inner}>"));
    }
    if let Some(rest) = hint.strip_prefix("list[") {
        let inner = shape_spelling_of_python_type(rest.strip_suffix(']')?)?;
        return Some(format!("Array<{inner}>"));
    }
    if let Some(rest) = hint.strip_prefix("dict[str, ") {
        let inner = shape_spelling_of_python_type(rest.strip_suffix(']')?)?;
        return Some(format!("HashMap<string, {inner}>"));
    }
    match hint {
        "int" => Some("int".to_string()),
        "float" => Some("number".to_string()),
        "bool" => Some("bool".to_string()),
        "str" => Some("string".to_string()),
        "None" => Some("none".to_string()),
        name if is_identifier(name) => Some(name.to_string()),
        _ => None,
    }
}

fn is_identifier(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .next()
            .is_some_and(|c| c.is_alphabetic() || c == '_')
        && s.chars().all(|c| c.is_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;
    use shape_abi_v1::foreign_types::{
        ForeignDirection, ForeignField, ForeignFunctionContract, ForeignParamContract, ForeignType,
        marshal_table,
    };

    /// ADR-019 §1 / #196 tripwire (1), Python side: every type in the
    /// marshaling table has a `.pyi` rendering, and that rendering carries
    /// enough information to recover the Shape type it came from — asserted per
    /// type, over a table the host generates mechanically, so a new marshal type
    /// with no stub mapping fails here.
    #[test]
    fn render_round_trips_every_table_entry() {
        let anon = AnonNames::default();
        for entry in marshal_table() {
            let rendered = python_type(&entry, &anon);
            let recovered = shape_spelling_of_python_type(&rendered).unwrap_or_else(|| {
                panic!(
                    "table entry `{}` rendered as `{}`, which maps back to no Shape type",
                    entry.shape_spelling(),
                    rendered
                )
            });
            assert_eq!(
                recovered,
                entry.shape_spelling(),
                "table entry `{}` rendered as `{}` and came back as `{}`",
                entry.shape_spelling(),
                rendered,
                recovered
            );
            // And the recovered spelling is one the host's classifier accepts,
            // so the round-trip closes through the real parser rather than
            // through this module's own idea of a Shape type.
            let direction = if entry.supports(ForeignDirection::Return) {
                ForeignDirection::Return
            } else {
                ForeignDirection::Argument
            };
            ForeignType::classify(&recovered, direction).unwrap_or_else(|e| {
                panic!("recovered spelling `{recovered}` is not classifiable: {e:?}")
            });
        }
    }

    #[test]
    fn every_scalar_has_a_distinct_python_hint() {
        let anon = AnonNames::default();
        let mut seen: Vec<String> = Vec::new();
        for scalar in ForeignScalar::ALL {
            let hint = python_type(&ForeignType::Scalar(*scalar), &anon);
            assert!(
                !seen.contains(&hint),
                "scalar {scalar:?} shares the hint `{hint}` with another scalar — the \
                 mapping would not be invertible"
            );
            seen.push(hint);
        }
    }

    fn contract_with(
        functions: Vec<ForeignFunctionContract>,
        types: Vec<ForeignType>,
    ) -> ForeignContractExport {
        let mut contract = ForeignContractExport::new("python");
        contract.functions = functions;
        contract.types = types;
        contract
    }

    #[test]
    fn a_declared_function_becomes_a_typed_def() {
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "add".to_string(),
                params: vec![
                    ForeignParamContract {
                        name: "a".to_string(),
                        ty: ForeignType::Scalar(ForeignScalar::Int),
                    },
                    ForeignParamContract {
                        name: "b".to_string(),
                        ty: ForeignType::Scalar(ForeignScalar::Number),
                    },
                ],
                returns: ForeignType::Scalar(ForeignScalar::Int),
            }],
            Vec::new(),
        );
        let stub = render_stub(&contract);
        assert!(
            stub.contains("def add(a: int, b: float) -> int: ..."),
            "stub must declare the function signature, got:\n{stub}"
        );
    }

    #[test]
    fn a_named_object_type_becomes_a_typed_dict() {
        let candle = ForeignType::Object {
            name: Some("Candle".to_string()),
            fields: Some(vec![
                ForeignField {
                    name: "open".to_string(),
                    ty: ForeignType::Scalar(ForeignScalar::Number),
                    optional: false,
                },
                ForeignField {
                    name: "symbol".to_string(),
                    ty: ForeignType::Scalar(ForeignScalar::String),
                    optional: false,
                },
            ]),
        };
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "analyze".to_string(),
                params: vec![ForeignParamContract {
                    name: "c".to_string(),
                    ty: ForeignType::Object {
                        name: Some("Candle".to_string()),
                        fields: None,
                    },
                }],
                returns: ForeignType::Scalar(ForeignScalar::Number),
            }],
            vec![candle],
        );
        let stub = render_stub(&contract);
        assert!(stub.contains("class Candle(TypedDict):"), "got:\n{stub}");
        assert!(stub.contains("    open: float"), "got:\n{stub}");
        assert!(stub.contains("    symbol: str"), "got:\n{stub}");
        assert!(
            stub.contains("def analyze(c: Candle) -> float: ..."),
            "got:\n{stub}"
        );
        // The class must precede its use, or the stub does not parse.
        assert!(
            stub.find("class Candle").unwrap() < stub.find("def analyze").unwrap(),
            "the class must be declared before the function that uses it:\n{stub}"
        );
    }

    #[test]
    fn a_type_whose_fields_were_not_exported_says_so() {
        let contract = contract_with(
            Vec::new(),
            vec![ForeignType::Object {
                name: Some("Bag".to_string()),
                fields: None,
            }],
        );
        let stub = render_stub(&contract);
        assert!(stub.contains("class Bag(TypedDict"), "got:\n{stub}");
        assert!(
            stub.contains("fields not exported"),
            "an unexportable type must be labelled, not silently emitted empty:\n{stub}"
        );
    }

    #[test]
    fn an_inline_object_literal_gets_a_declared_name_before_use() {
        let literal = ForeignType::Object {
            name: None,
            fields: Some(vec![ForeignField {
                name: "value".to_string(),
                ty: ForeignType::Scalar(ForeignScalar::Number),
                optional: false,
            }]),
        };
        let contract = contract_with(
            vec![ForeignFunctionContract {
                name: "measure".to_string(),
                params: Vec::new(),
                returns: literal,
            }],
            Vec::new(),
        );
        let stub = render_stub(&contract);
        assert!(
            stub.contains("class _ShapeObject1(TypedDict):"),
            "got:\n{stub}"
        );
        assert!(stub.contains("    value: float"), "got:\n{stub}");
        assert!(
            stub.contains("def measure() -> _ShapeObject1: ..."),
            "got:\n{stub}"
        );
    }
}
